{
  "containers": {
    "cna": {
      "providerMetadata": {
        "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09"
      },
      "title": "Unauthorised access to dedicated resources in Quota plugin",
      "problemTypes": [
        {
          "descriptions": [
            {
              "description": "CWE-269: Improper Privilege Management",
              "lang": "en",
              "cweId": "CWE-269",
              "type": "CWE"
            }
          ]
        }
      ],
      "source": {
        "discovery": "UNKNOWN"
      },
      "affected": [
        {
          "vendor": "Apache Software Foundation",
          "product": "Apache CloudStack",
          "versions": [
            {
              "status": "affected",
              "version": "4.20.0.0",
              "lessThan": "4.20.1.0",
              "versionType": "semver"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "descriptions": [
        {
          "value": "The CloudStack Quota plugin has an improper privilege management logic in version 4.20.0.0. Anyone with authenticated user-account access in CloudStack 4.20.0.0 environments, where this plugin is enabled and have access to specific APIs can enable or disable reception of quota-related emails for any account in the environment and list their configurations.\n\nQuota plugin users using CloudStack 4.20.0.0 are recommended to upgrade to CloudStack version 4.20.1.0, which fixes this issue.",
          "lang": "en",
          "supportingMedia": [
            {
              "type": "text/html",
              "base64": false,
              "value": "The CloudStack Quota plugin has an improper privilege management logic in version 4.20.0.0. Anyone with authenticated user-account access in CloudStack 4.20.0.0 environments, where this plugin is enabled and have access to specific APIs can enable or disable reception of quota-related emails for any account in the environment and list their configurations.<br><br>Quota plugin users using CloudStack 4.20.0.0 are recommended to upgrade to CloudStack version 4.20.1.0, which fixes this issue."
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://cloudstack.staged.apache.org/blog/cve-advisories-4.19.3.0-4.20.1.0",
          "tags": [
            "vendor-advisory"
          ]
        },
        {
          "url": "https://www.shapeblue.com/shapeblue-security-advisory-cloudstack-4-19-3-0-and-4-20-1-0/",
          "tags": [
            "third-party-advisory"
          ]
        },
        {
          "url": "https://lists.apache.org/thread/y3qnwn59t8qggtdohv7k7vw39bgb3d60",
          "tags": [
            "mailing-list"
          ]
        }
      ],
      "metrics": [
        {
          "format": "CVSS",
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ],
          "cvssV4_0": {
            "version": "4.0",
            "attackVector": "NETWORK",
            "attackComplexity": "LOW",
            "attackRequirements": "PRESENT",
            "privilegesRequired": "LOW",
            "userInteraction": "NONE",
            "vulnConfidentialityImpact": "NONE",
            "subConfidentialityImpact": "NONE",
            "vulnIntegrityImpact": "LOW",
            "subIntegrityImpact": "NONE",
            "vulnAvailabilityImpact": "LOW",
            "subAvailabilityImpact": "NONE",
            "Safety": "NEGLIGIBLE",
            "Automatable": "NO",
            "Recovery": "USER",
            "valueDensity": "DIFFUSE",
            "vulnerabilityResponseEffort": "LOW",
            "providerUrgency": "AMBER",
            "baseSeverity": "LOW",
            "baseScore": 2.3,
            "vectorString": "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/S:N/AU:N/R:U/V:D/RE:L/U:Amber"
          }
        }
      ],
      "credits": [
        {
          "lang": "en",
          "value": "Fabricio Duarte <fabricio.duarte.jr@gmail.com>",
          "type": "finder"
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.2.0"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2025-22829",
    "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
    "serial": 1,
    "state": "PUBLISHED"
  },
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1"
}